### ISSUE TITLE
Border not rounded

### ISSUE THREAD

**Issue by eeeXun** [ray-x/lsp_signature.nvim#190]
Already set following in `on_attach`
```lua
   require("lsp_signature").on_attach({
       bind = true,
       border = "rounded",
   })
```
But the border sometimes not get rounded.
![2022-06-15_01-43-02](https://user-images.githubusercontent.com/58657914/173653028-1112d8e1-8aff-4077-ba06-c5d2de7335b5.gif)

**Comment by rodhash** [comment]
Had same issue, running latest version `3755b08`

**Comment by ray-x** [comment]
this one should be fixed in latest

**Comment by eeeXun** [comment]
Hi @ray-x , the problem still exist

https://user-images.githubusercontent.com/58657914/179659170-61514583-be6b-40be-b710-2ffe858ebbb6.mp4

**Comment by ray-x** [comment]
Did not notice the border missing when CursorHoldI autocmd. It should be fixed now.

**Comment by eeeXun** [comment]
@ray-x I don't encounter any problem until now. Thank you for your fix!
